/*
자세히 하는 버전 

DROP TABLE BOOK;
DROP TABLE BOOKKIND;
CREATE TABLE BOOKKIND(
	BOOK_KIND	NUMBER(3)	PRIMARY KEY,
	KIND_NAME	VARCHAR2(30),
	LOCATION	VARCHAR2(50)
);

CREATE TABLE BOOK (
	BOOK_ID				VARCHAR2(30)	PRIMARY KEY, -- 책ID
	BOOK_KIND			NUMBER(3)		REFERENCES BOOKKIND(BOOK_KIND), -- 책분류
	BOOK_TITLE			VARCHAR2(60)	NOT NULL, -- 책제목
	BOOK_PRICE			NUMBER(6)		NOT NULL, -- 책 가격
	BOOK_COUNT			NUMBER(6)		NOT NULL, -- 책 재고 수량
	AUTHOR				VARCHAR2(30)	NOT NULL, -- 저자
	PUBLIISHING_COM		VARCHAR2(30)	NOT NULL, -- 출판사
	PUBLIISHING_DATE	DATE			NOT NULL, -- 출판일
	BOOK_IMAGE1			VARCHAR2(30) 	DEFAULT 'NOTHING.jpg'	NOT NULL,  -- 책대표이미지
	BOOK_IMAGE2			VARCHAR2(30) 	DEFAULT 'noImg.png'	NOT NULL,  -- 책 이미지
	BOOK_CONTENT		VARCHAR2(4000),	-- 책소개
	BOOK_DISCOUNT		NUMBER(3)		DEFAULT 0,
	BOOK_RDATE			DATE			DEFAULT SYSDATE -- 등록일
	
);


SELECT * FROM BOOKKIND;
*/

DROP TABLE BOOK;
DROP TABLE BOOKKIND;
DROP SEQUENCE BOOK_SEQ;

CREATE SEQUENCE BOOK_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
-- bCONTENT    CLOB, -- 용량이 클때에는 CLOB으로
CREATE TABLE BOOK (
    bID         NUMBER(7)       PRIMARY KEY, -- 책ID
    bTITLE      VARCHAR2(30)    NOT NULL,    -- 책제목
    bPRICE      NUMBER(7)       NOT NULL,    -- 책 가격
    bIMAGE1     VARCHAR2(30)    DEFAULT 'NOTHING.JPG'   NOT NULL,  -- 책대표이미지
    bIMAGE2     VARCHAR2(30)    DEFAULT 'noImg.png'   NOT NULL,    -- 책 이미지
    bCONTENT    VARCHAR2(4000), -- 책 설명
    bDISCOUNT   NUMBER(3)       NOT NULL,  -- 할인율
    bRDATE      DATE            DEFAULT SYSDATE -- 책등록일
);

-- 책등록
-- 이미지를 모두 등록한경우
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.nextval, '이것이 자바다', 20000, 'NOTHING.JPG', 'noImg.png', '딱좋아!', 10);

-- 이미지를 bImage1만 등록한경우
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.nextval, '이것이 JSP다', 20000, 'NOTHING.JPG', '딱좋아!', 15);

-- 이미지를 bImage2만 등록한경우
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.nextval, '이것이 JAVA다', 19000, 'noImg.png', '딱좋아!', 10);
    
-- 이미지를 모두 등록하지 않은 경우
INSERT INTO BOOK (bID, bTITLE, bPRICE, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.nextval, '이것이 javascript다', 22000, '딱좋아!', 20);
    
SELECT * FROM BOOK;

-- 책목록
SELECT * FROM BOOK ORDER BY bRDATE DESC;    -- 신착도서순으로

-- 책목록(TOP-N) 페이징처리용
SELECT * FROM BOOK ORDER BY bRDATE DESC; -- 1단계(listBoard())

SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY bRDATE DESC) A; -- 2단계

SELECT * FROM (SELECT ROWNUM RN, A.* FROM(SELECT * FROM BOOK ORDER BY bRDATE DESC) A)
    WHERE RN BETWEEN 1 AND 3; --  최종 TOP-N 구문 ((listBoard(s , e))

-- 등록된 책 갯수
SELECT COUNT(*) FROM BOOK;

-- bID로 책 가져오기
SELECT * FROM BOOK WHERE bID = '1';


COMMIT;









