-- 태이블 생성
DROP TABLE FRIEND;

CREATE TABLE FRIEND (
    SNO     NUMBER(4) PRIMARY KEY,
    NAME    VARCHAR2(20) NOT NULL,
    TEL     VARCHAR2(13) UNIQUE
);

SELECT * FROM FRIEND;

-- 시퀀스생성
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
  INCREMENT BY 1 
  MAXVALUE 9999 
  NOCYCLE
  NOCACHE;
  
-- 데이터 입력
INSERT INTO FRIEND VALUES (FRIEND_SEQ.nextval, '홍길동', '010-9999-9999');

-- 데이터 검색
SELECT * FROM FRIEND;
commit;

