-- CUSTOMER 테이블의 회원 가입 데이터 DUMMY
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH )
    VALUES ('BBB', '111', '홍길동', '010-9999-9999', 'HONG@HONG.COM', '서울시 종로구', 'M', '2020-02-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH )
    VALUES ('CCC', '111', '라길동', '010-9999-9999', 'HONG@HONG.COM', '서울시 종로구', 'M', '2020-02-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH )
    VALUES ('DDD', '111', '고길동', '010-9999-9999', 'HONG@HONG.COM', '서울시 종로구', 'M', '2020-02-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH )
    VALUES ('EEE', '111', '장길동', '010-9999-9999', 'HONG@HONG.COM', '서울시 종로구', 'M', '2020-02-01');
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH )
    VALUES ('FFF', '111', '헐크', '010-9999-9999', 'HONG@HONG.COM', '서울시 종로구', 'M', '2020-02-01');

INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH )
    VALUES ('aa1', '111', '캡아', '010-9999-9999', 'HONG@HONG.COM', '서울시 종로구', 'M', '2020-02-01');

INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH )
    VALUES ('aa2', '111', '아이언맨', '010-9999-9999', 'HONG@HONG.COM', '서울시 종로구', 'M', '2020-02-01');

INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH )
    VALUES ('aa3', '111', '토르', '010-9999-9999', 'HONG@HONG.COM', '서울시 종로구', 'M', '2020-02-01');

INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH )
    VALUES ('aa4', '111', '닥스', '010-9999-9999', 'HONG@HONG.COM', '서울시 종로구', 'M', '2020-02-01');

INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH )
    VALUES ('aa5', '111', '팔콘', '010-9999-9999', 'HONG@HONG.COM', '서울시 종로구', 'M', '2020-02-01');
    
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH )
    VALUES ('aa6', '111', '에이션트원', '010-9999-9999', 'HONG@HONG.COM', '서울시 종로구', 'M', '2020-02-01');
    
-- BOOK 테이블의 책 등록 데이터 DUMMY
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.nextval, '이것이 자바냥', 15000, 'NOTHING.JPG', 'noImg.png', '자바냥', 10);

INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.nextval, 'JAVA IS GOD', 18000, 'NOTHING.JPG', 'noImg.png', '자바냥', 10);

INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.nextval, '이것이 JSP', 25000, 'NOTHING.JPG', 'noImg.png', 'JSPPP', 10);    
    
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.nextval, '이것이 HTML', 10000, 'NOTHING.JPG', 'noImg.png', 'HTML5!', 10);
    
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.nextval, 'JAVASCRIPT BAAM', 50000, 'NOTHING.JPG', 'noImg.png', 'BAAM', 10);


-- FILEBOARD 게시글 등록 DUMMY
INSERT INTO FILEBOARD (fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP) 
        VALUES (FILEBOARD_SEQ.nextval, 'AAA', '내가 홍길동이다', '아버지를 아버지라 못하는데 어찌해야 하나요?', 
                NULL, '111', FILEBOARD_SEQ.CURRVAL, 0, 0, '192.168.20.59');

INSERT INTO FILEBOARD (fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP) 
        VALUES (FILEBOARD_SEQ.nextval, 'BBB', 'BBB제목', 'BBB내용', 
                NULL, '111', FILEBOARD_SEQ.CURRVAL, 0, 0, '192.168.20.59');

INSERT INTO FILEBOARD (fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP) 
        VALUES (FILEBOARD_SEQ.nextval, 'CCC', 'CCC제목', 'CCC내용', 
                NULL, '111', FILEBOARD_SEQ.CURRVAL, 0, 0, '192.168.20.59');

INSERT INTO FILEBOARD (fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP) 
        VALUES (FILEBOARD_SEQ.nextval, 'DDD', 'DDD제목', 'DDD내용', 
                NULL, '111', FILEBOARD_SEQ.CURRVAL, 0, 0, '192.168.20.59');

INSERT INTO FILEBOARD (fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP) 
        VALUES (FILEBOARD_SEQ.nextval, 'EEE', 'EEE제목', 'EEE내용', 
                NULL, '111', FILEBOARD_SEQ.CURRVAL, 0, 0, '192.168.20.59');
                
INSERT INTO FILEBOARD (fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP) 
        VALUES (FILEBOARD_SEQ.nextval, 'AAA', 'files', 'files', 
                'test.PNG', '111', FILEBOARD_SEQ.CURRVAL, 0, 0, '192.168.20.59');
                
-- 2번 글에대한 첫번째 답변글
INSERT INTO FILEBOARD (fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP) 
        VALUES (FILEBOARD_SEQ.nextval, 'AAA', '내가 홍길동이다', '아버지를 아버지라 못하는데 어찌해야 하나요?', 
                NULL, '111', 2, 1, 1, '192.168.20.59'); 























